### ISSUE TITLE
增加 `GODOC_LOCAL_ROOT` 环境变量

### ISSUE THREAD

**Issue by chai2010** [golang-china/golangdoc#1]
用于指定本地翻译文件所在的位置。
缺省为: `$(GOROOT)/translates`

**Comment by achun** [comment]
建议优先次序:
 1. 环境变量             $GODOC_LOCAL_ROOT
 2. 第一个GOPATH  $(GOPATH)/translates
 3. $(GOROOT)/translates

**Comment by chai2010** [comment]
感觉可以是多个目录的集合。
因为不同的语言和不同的包的翻译可能不在同一个目录。

**Comment by chai2010** [comment]
https://github.com/golang-china/golangdoc/commit/86b1f5a4293bdea293eb848915a82539a38fa2fe 增加了从命令后参数和环境变量指定翻译目录的特性。
